---
apiVersion: v1
kind: Service
metadata:
  annotations:
    discovery.3scale.net/path: /camel
    discovery.3scale.net/discovery-version: v1
    discovery.3scale.net/description-path: /api-docs
    discovery.3scale.net/scheme: http
    discovery.3scale.net/port: "8080"
    fabric8.io/git-commit: c53230a7c7a75ed144bc5f4136d894cfdd853124
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    discovery.3scale.net: "true"
    app: rest-device
    provider: fabric8
    version: 1.0.0
    group: org.mycompany
  name: rest-device
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-device
    provider: fabric8
    group: org.mycompany
