---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: c53230a7c7a75ed144bc5f4136d894cfdd853124
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    app: soap-fulfillment
    provider: fabric8
    version: 1.0.0
    group: org.mycompany
  name: soap-fulfillment
spec:
  ports:
  - port: 18080
    protocol: TCP
    targetPort: 18080
  selector:
    app: soap-fulfillment
    provider: fabric8
    group: org.mycompany
